# Focused contracts for static export, diagnostics, source/test execution, and
# ipynb/Rmd/qmd conversion. These tests deliberately avoid HTTP routes; the
# live export route is owned by the server phase.

export_test_notebook <- function(path) {
  writeLines(c(
    "# ---", "# title: Export demo", "# ---", "# %% [markdown]",
    "# # A heading", "# %%", "x <- 1", "# %%", "x + 1"
  ), path, useBytes = TRUE)
  path
}

test_that("all static exporters write their declared formats", {
  td <- tempfile("alder-export-")
  dir.create(td)
  nb_path <- export_test_notebook(file.path(td, "demo.R"))
  outputs <- setNames(lapply(c("html", "md", "script", "ipynb", "qmd", "session"),
                             function(fmt) {
                               out <- file.path(td, paste0("demo.", fmt,
                                                            if (fmt == "script") "R" else ""))
                               alder:::alder_export(nb_path, fmt, out = out,
                                                    include_code = TRUE)
                               out
                             }),
                     c("html", "md", "script", "ipynb", "qmd", "session"))
  expect_true(all(vapply(outputs, file.exists, logical(1))))
  expect_true(startsWith(paste(readLines(outputs$html, warn = FALSE), collapse = "\n"),
                         "<!DOCTYPE html"))
  expect_match(paste(readLines(outputs$html, warn = FALSE), collapse = "\n"),
               "A heading")
  expect_match(paste(readLines(outputs$script, warn = FALSE), collapse = "\n"),
               "x <- 1")
  markdown_lines <- readLines(outputs$md, warn = FALSE)
  expect_identical(sum(markdown_lines == "# A heading"), 1L)
  expect_false(any(markdown_lines == "# # A heading"))
  ip <- jsonlite::fromJSON(outputs$ipynb, simplifyVector = FALSE)
  expect_length(ip$cells, 3L)
  expect_identical(vapply(ip$cells, `[[`, character(1), "cell_type"),
                   c("markdown", "code", "code"))
  session <- jsonlite::fromJSON(outputs$session, simplifyVector = FALSE)
  expect_equal(session$version, 1)
  expect_length(session$cells, 3L)
})

test_that("static image exports always carry a useful fallback alternative", {
  td <- tempfile("alder-export-alt-")
  dir.create(td)
  artifact <- file.path(td, "plot.png")
  writeBin(as.raw(c(137L, 80L, 78L, 71L)), artifact)
  output <- list(kind = "image", artifact = basename(artifact))

  html <- alder:::export_output_html(
    output, td, alt_fallback = "Plot generated by R in cell analysis"
  )
  expect_match(html, 'alt="Plot generated by R in cell analysis"', fixed = TRUE)

  files <- file.path(td, "report_files")
  markdown <- alder:::export_output_markdown(
    output, td, files, alt_fallback = "Plot generated by R in cell analysis"
  )
  expect_match(markdown, "![Plot generated by R in cell analysis]", fixed = TRUE)
})

test_that("ipynb export converts back with cell types and bodies", {
  td <- tempfile("alder-roundtrip-")
  dir.create(td)
  source <- export_test_notebook(file.path(td, "roundtrip.R"))
  ipynb <- file.path(td, "roundtrip.ipynb")
  alder:::alder_export(source, "ipynb", out = ipynb)
  converted <- file.path(td, "converted.R")
  alder:::alder_convert(ipynb, out = converted)
  original <- alder:::read_notebook(source)
  result <- alder:::read_notebook(converted)
  expect_identical(vapply(result$cells, `[[`, character(1), "type"),
                   vapply(original$cells, `[[`, character(1), "type"))
  expect_identical(lapply(result$cells, `[[`, "body"),
                   lapply(original$cells, `[[`, "body"))
})

test_that("Rmd and qmd chunks map supported alder options", {
  td <- tempfile("alder-rmd-")
  dir.create(td)
  for (ext in c("Rmd", "qmd")) {
    source <- file.path(td, paste0("input.", ext))
    writeLines(c(
      "---", "title: Chunk demo", "custom: retained", "---", "",
      "A paragraph.", "", "```{r sample, echo=FALSE, eval=FALSE, cache=TRUE}",
      "x <- 1", "```"
    ), source, useBytes = TRUE)
    converted <- file.path(td, paste0("output-", ext, ".R"))
    alder:::alder_convert(source, out = converted)
    nb <- alder:::read_notebook(converted)
    expect_identical(nb$metadata$title, "Chunk demo")
    expect_identical(nb$metadata$custom, "retained")
    code <- nb$cells[[2L]]
    expect_identical(code$type, "code")
    expect_identical(code$options$name, "sample")
    expect_true(isTRUE(code$options$hide_code))
    expect_true(isTRUE(code$options$disabled))
    expect_false("cache" %in% names(code$options))
  }
})

test_that("alder_check prints diagnostics and rejects duplicate definitions", {
  td <- tempfile("alder-check-")
  dir.create(td)
  good <- export_test_notebook(file.path(td, "good.R"))
  clean <- capture.output(result <- alder:::alder_check(good))
  expect_length(clean, 0L)
  expect_equal(nrow(result), 0L)
  bad <- file.path(td, "bad.R")
  writeLines(c("# %%", "x <- 1", "# %%", "x <- 2"), bad, useBytes = TRUE)
  printed <- capture.output(expect_error(alder:::alder_check(bad),
                                         "alder_check found 2 error diagnostics"))
  expect_true(any(grepl("duplicate-definition", printed, fixed = TRUE)))
})

test_that("alder_source evaluates topologically and alder_test runs marked cells", {
  td <- tempfile("alder-source-")
  dir.create(td)
  path <- file.path(td, "source.R")
  writeLines(c("# %%", "x <- 1", "# %%", "#| test: true",
               "testthat::expect_equal(x, 1)"), path, useBytes = TRUE)
  env <- new.env(parent = globalenv())
  expect_invisible(alder:::alder_source(path, env))
  results <- alder:::alder_test(path)
  expect_s3_class(results, "testthat_results")
  expect_length(results, 1L)
  expect_true(any(vapply(results[[1L]]$results, inherits,
                          logical(1), "expectation_success")))
})

test_that("alder_test executes setup and test cells once in dependency order", {
  td <- tempfile("alder-test-single-pass-")
  dir.create(td)
  path <- file.path(td, "single-pass.R")
  effect <- file.path(td, "effects.txt")
  literal <- function(value) paste(utils::capture.output(dput(value)), collapse = "")
  writeLines(c(
    "# %%", paste0("effect_path <- ", literal(effect)),
    "# %%", "writeLines('setup-one', effect_path)",
    "# %%", "#| name: first", "#| test: true",
    "cat('test-one\\n', file = effect_path, append = TRUE)",
    "testthat::expect_identical(getwd(), dirname(effect_path))",
    "testthat::expect_identical(readLines(effect_path), c('setup-one', 'test-one'))",
    "first_ready <- TRUE",
    "# %%", "after_first <- first_ready",
    "cat('setup-two\\n', file = effect_path, append = TRUE)",
    "# %%", "#| name: second", "#| test: true",
    "cat('test-two\\n', file = effect_path, append = TRUE)",
    "testthat::expect_true(after_first)",
    "testthat::expect_identical(readLines(effect_path), c('setup-one', 'test-one', 'setup-two', 'test-two'))"
  ), path, useBytes = TRUE)

  results <- alder:::alder_test(path)
  expect_s3_class(results, "testthat_results")
  expect_length(results, 2L)
  expect_identical(vapply(results, `[[`, character(1), "test"), c("first", "second"))
  expect_identical(readLines(effect, warn = FALSE),
                   c("setup-one", "test-one", "setup-two", "test-two"))
})

test_that("alder_test propagates testthat failures for nonzero callers", {
  td <- tempfile("alder-test-status-")
  dir.create(td)
  path <- file.path(td, "failing-test.R")
  writeLines(c(
    "# %%", "#| test: true",
    "testthat::expect_identical(1L, 2L)"
  ), path, useBytes = TRUE)

  before <- ls(alder:::ALDER_TEST_REGISTRY, all.names = TRUE)
  err <- tryCatch(alder:::alder_test(path), error = identity)
  expect_s3_class(err, "alder_test_failure")
  expect_s3_class(err, "alder_error")
  expect_s3_class(err$parent, "expectation_failure")
  expect_identical(err$code, "test_failed")
  expect_match(conditionMessage(err), "Expected 1L to be identical to 2L", fixed = TRUE)
  expect_identical(ls(alder:::ALDER_TEST_REGISTRY, all.names = TRUE), before)
})

test_that("alder_test framework bookkeeping preserves notebook RNG state", {
  td <- tempfile("alder-test-rng-")
  dir.create(td)
  path <- file.path(td, "rng.R")
  writeLines(c("# %%", "#| test: true", "testthat::expect_true(TRUE)"),
             path, useBytes = TRUE)
  seed_name <- paste0(".Random", ".seed")
  had_seed <- exists(seed_name, envir = .GlobalEnv, inherits = FALSE)
  previous_seed <- if (had_seed) get(seed_name, envir = .GlobalEnv) else NULL
  on.exit({
    if (had_seed) assign(seed_name, previous_seed, envir = .GlobalEnv)
    else rm(list = seed_name, envir = .GlobalEnv)
  }, add = TRUE)
  set.seed(20260904L)
  expected <- runif(2L)
  set.seed(20260904L)
  alder:::alder_test(path)
  observed <- runif(2L)
  expect_identical(observed, expected)
})

test_that("alder_test turns unexpected test warnings into failures", {
  td <- tempfile("alder-test-warning-")
  dir.create(td)
  path <- file.path(td, "warning.R")
  writeLines(c(
    "# %%", "#| test: true", "warning('test warning sentinel')",
    "testthat::expect_true(TRUE)"
  ), path, useBytes = TRUE)

  err <- tryCatch(alder:::alder_test(path), error = identity)
  expect_s3_class(err, "alder_test_warning")
  expect_s3_class(err, "alder_error")
  expect_s3_class(err$parent, "expectation_warning")
  expect_identical(err$code, "test_failed")
  expect_match(conditionMessage(err), "test warning sentinel", fixed = TRUE)
})

test_that("alder_test reports success and failure through subprocess status", {
  td <- tempfile("alder-test-subprocess-")
  dir.create(td)
  # R CMD check relocates tests outside the loaded package. Carry its actual
  # namespace path and dependency libraries into the vanilla child instead.
  package_path <- normalizePath(
    getNamespaceInfo(asNamespace("alder"), "path"), mustWork = TRUE
  )
  libraries <- file.path(td, "libraries.rds")
  saveRDS(.libPaths(), libraries)
  runner <- file.path(td, "run-tests.R")
  writeLines(c(
    "args <- commandArgs(trailingOnly = TRUE)",
    ".libPaths(readRDS(args[[2L]]))",
    "if (file.exists(file.path(args[[1L]], 'Meta', 'package.rds'))) {",
    "  library(alder, lib.loc = dirname(args[[1L]]))",
    "} else {",
    "  pkgload::load_all(args[[1L]], quiet = TRUE)",
    "}",
    "stopifnot(identical(",
    "  normalizePath(getNamespaceInfo(asNamespace('alder'), 'path')),",
    "  normalizePath(args[[1L]])",
    "))",
    "alder::alder_test(args[[3L]])"
  ), runner, useBytes = TRUE)
  good <- file.path(td, "good.R")
  bad <- file.path(td, "bad.R")
  writeLines(c("# %%", "#| test: true", "testthat::expect_identical(1L, 1L)"),
             good, useBytes = TRUE)
  writeLines(c("# %%", "#| test: true", "testthat::expect_identical(1L, 2L)"),
             bad, useBytes = TRUE)
  run <- function(path) processx::run(
    file.path(R.home("bin"), "Rscript"),
    c("--vanilla", runner, package_path, libraries, path),
    error_on_status = FALSE, echo = FALSE
  )

  success <- run(good)
  failure <- run(bad)
  expect_identical(success$status, 0L)
  expect_gt(failure$status, 0L)
  expect_match(paste(failure$stdout, failure$stderr),
               "Expected 1L to be identical to 2L", fixed = TRUE)
})

test_that("alder_check and alder_source accept bounded literal mutation", {
  td <- tempfile("alder-literal-mutation-")
  dir.create(td)
  path <- file.path(td, "literal-mutation.R")
  writeLines(c(
    "# %%", "assigned_result <- assigned_value + 1L",
    "# %%", "assign('assigned_value', 41L)",
    "# %%", "removed <- 1L", "rm('removed')"
  ), path, useBytes = TRUE)

  expect_length(capture.output(diagnostics <- alder:::alder_check(path)), 0L)
  expect_equal(nrow(diagnostics), 0L)
  env <- new.env(parent = globalenv())
  expect_invisible(alder:::alder_source(path, env))
  expect_identical(env$assigned_result, 42L)
  expect_false(exists("removed", envir = env, inherits = FALSE))
})

test_that("converted disabled cells and descendants stay out of alder_source", {
  td <- tempfile("alder-disabled-source-")
  dir.create(td)
  source <- file.path(td, "input.Rmd")
  converted <- file.path(td, "converted.R")
  disabled_effect <- file.path(td, "disabled-ran")
  descendant_effect <- file.path(td, "transitive-descendant-ran")
  literal <- function(value) paste(utils::capture.output(dput(value)), collapse = "")
  writeLines(c(
    "---", "title: Disabled source", "---", "# Narrative",
    "```{r setup}", "input <- 40L", "```",
    "```{r disabled, eval=FALSE}",
    "blocked_value <- {",
    paste0("  writeLines('disabled ran', ", literal(disabled_effect), ")"),
    "  stop('disabled chunk ran')", "}", "```",
    "```{r dependent}",
    "blocked_intermediate <- blocked_value + 1L", "```",
    "```{r transitive_descendant}",
    "blocked_answer <- blocked_intermediate + 1L",
    paste0("writeLines('descendant ran', ", literal(descendant_effect), ")"),
    "```",
    "```{r independent}", "message('independent message')",
    "warning('independent warning')", "answer <- input + 2L", "answer", "```"
  ), source, useBytes = TRUE)

  alder:::alder_convert(source, out = converted)
  nb <- alder:::read_notebook(converted)
  expect_true(isTRUE(nb$cells[[3L]]$options$disabled))
  env <- new.env(parent = globalenv())
  expect_warning(
    expect_message(
      expect_invisible(alder:::alder_source(converted, env)),
      "independent message", fixed = TRUE
    ),
    "independent warning", fixed = TRUE
  )
  expect_identical(env$answer, 42L)
  expect_false(exists("blocked_value", env, inherits = FALSE))
  expect_false(exists("blocked_intermediate", env, inherits = FALSE))
  expect_false(exists("blocked_answer", env, inherits = FALSE))
  expect_false(file.exists(disabled_effect))
  expect_false(file.exists(descendant_effect))
})

test_that("alder_test excludes disabled tests and their descendants", {
  td <- tempfile("alder-disabled-test-")
  dir.create(td)
  path <- file.path(td, "tests.R")
  disabled_effect <- file.path(td, "disabled-test-ran")
  descendant_effect <- file.path(td, "transitive-test-ran")
  literal <- function(value) paste(utils::capture.output(dput(value)), collapse = "")
  writeLines(c(
    "# %%", "input <- 40L",
    "# %%", "#| name: disabled_test", "#| disabled: true", "#| test: true",
    "blocked_value <- {",
    paste0("  writeLines('disabled ran', ", literal(disabled_effect), ")"),
    "  stop('disabled test ran')", "}",
    "# %%", "#| name: dependent_test", "#| test: true",
    "blocked_intermediate <- blocked_value + 1L",
    "testthat::expect_equal(blocked_intermediate, 42L)",
    "# %%", "#| name: transitive_test", "#| test: true",
    "blocked_answer <- blocked_intermediate + 1L",
    paste0("writeLines('descendant ran', ", literal(descendant_effect), ")"),
    "testthat::expect_equal(blocked_answer, 42L)",
    "# %%", "#| name: independent_test", "#| test: true",
    "testthat::expect_equal(input + 2L, 42L)"
  ), path, useBytes = TRUE)

  results <- alder:::alder_test(path)
  expect_s3_class(results, "testthat_results")
  expect_length(results, 1L)
  expect_identical(results[[1L]]$test, "independent_test")
  expect_true(any(vapply(results[[1L]]$results, inherits,
                         logical(1), "expectation_success")))
  expect_false(file.exists(disabled_effect))
  expect_false(file.exists(descendant_effect))
})

test_that("alder_source errors identify the cell, call, and traceback", {
  td <- tempfile("alder-source-error-")
  dir.create(td)
  path <- file.path(td, "source.R")
  writeLines(c(
    "# %%",
    "inner_failure <- function() stop('deep failure')",
    "outer_failure <- function() inner_failure()",
    "outer_failure()"
  ), path, useBytes = TRUE)
  err <- tryCatch(alder:::alder_source(path), error = identity)
  expect_s3_class(err, "alder_cell_error")
  expect_identical(err$cell, "cell-1")
  expect_match(conditionMessage(err), "deep failure", fixed = TRUE)
  expect_match(paste(deparse(conditionCall(err)), collapse = " "),
               "inner_failure", fixed = TRUE)
  expect_gt(length(err$alder_trace), 0L)
  expect_lte(length(err$alder_trace), 40L)
})

test_that("unsupported conversion fails with convert_failed", {
  td <- tempfile("alder-convert-error-")
  dir.create(td)
  path <- file.path(td, "input.txt")
  writeLines("not a notebook", path)
  expect_error(alder:::alder_convert(path), class = "alder_error")
  err <- tryCatch(alder:::alder_convert(path), error = identity)
  expect_identical(err$code, "convert_failed")
})

test_that("export and conversion reject input aliases before any execution", {
  td <- tempfile("alder-output-alias-")
  dir.create(td)
  file_bytes <- function(path) readBin(path, "raw", n = file.info(path)$size)
  effect <- file.path(td, "export-ran")
  literal <- function(value) paste(utils::capture.output(dput(value)), collapse = "")
  export_input <- file.path(td, "export-input.R")
  writeLines(c(
    "# %%",
    paste0("writeLines('ran', ", literal(effect), ")")
  ), export_input, useBytes = TRUE)
  convert_inputs <- list(
    ipynb = file.path(td, "convert-input.ipynb"),
    rmd = file.path(td, "convert-input.Rmd"),
    qmd = file.path(td, "convert-input.qmd")
  )
  jsonlite::write_json(list(
    cells = list(list(cell_type = "code", metadata = list(),
                      source = I(c("x <- 1\n")), outputs = list(),
                      execution_count = NULL)),
    metadata = list(), nbformat = 4L, nbformat_minor = 5L
  ), convert_inputs$ipynb, auto_unbox = TRUE, pretty = TRUE, null = "null")
  writeLines(c("# Conversion input", "", "```{r}", "x <- 1", "```"),
             convert_inputs$rmd, useBytes = TRUE)
  writeLines(c("# Conversion input", "", "```{r}", "x <- 1", "```"),
             convert_inputs$qmd, useBytes = TRUE)
  export_original <- file_bytes(export_input)
  convert_originals <- lapply(convert_inputs, file_bytes)

  check_rejected <- function(expr, code) {
    err <- tryCatch(force(expr), error = identity)
    expect_s3_class(err, "alder_error")
    expect_identical(err$code, code)
    expect_identical(conditionMessage(err), "output path must not refer to input file")
  }

  for (format in alder:::export_formats) {
    check_rejected(alder:::alder_export(export_input, format, out = export_input),
                   "export_failed")
    expect_identical(file_bytes(export_input), export_original)
  }
  check_rejected(alder:::alder_export(
    export_input, "script",
    out = file.path(dirname(export_input), ".", basename(export_input))
  ), "export_failed")
  expect_identical(file_bytes(export_input), export_original)
  expect_false(file.exists(effect))
  for (i in seq_along(convert_inputs)) {
    convert_input <- convert_inputs[[i]]
    check_rejected(alder:::alder_convert(convert_input, out = convert_input),
                   "convert_failed")
    expect_identical(file_bytes(convert_input), convert_originals[[i]])
  }
  check_rejected(alder:::alder_convert(
    convert_inputs$qmd,
    out = file.path(dirname(convert_inputs$qmd), ".", basename(convert_inputs$qmd))
  ), "convert_failed")
  expect_identical(file_bytes(convert_inputs$qmd), convert_originals$qmd)

  export_symlink <- file.path(td, "export-symlink.R")
  if (isTRUE(file.symlink(export_input, export_symlink))) {
    check_rejected(alder:::alder_export(export_input, "script", out = export_symlink),
                   "export_failed")
    expect_identical(file_bytes(export_input), export_original)
  }
  convert_symlink <- file.path(td, "convert-symlink.qmd")
  if (isTRUE(file.symlink(convert_inputs$qmd, convert_symlink))) {
    check_rejected(alder:::alder_convert(convert_inputs$qmd, out = convert_symlink),
                   "convert_failed")
    expect_identical(file_bytes(convert_inputs$qmd), convert_originals$qmd)
  }

  export_hardlink <- file.path(td, "export-hardlink.R")
  if (isTRUE(file.link(export_input, export_hardlink))) {
    check_rejected(alder:::alder_export(export_input, "script", out = export_hardlink),
                   "export_failed")
    expect_identical(file_bytes(export_input), export_original)
  }
  convert_hardlink <- file.path(td, "convert-hardlink.qmd")
  if (isTRUE(file.link(convert_inputs$qmd, convert_hardlink))) {
    check_rejected(alder:::alder_convert(convert_inputs$qmd, out = convert_hardlink),
                   "convert_failed")
    expect_identical(file_bytes(convert_inputs$qmd), convert_originals$qmd)
  }
  expect_false(file.exists(effect))
})

test_that("export and conversion stage replacements and preserve destinations on failure", {
  td <- tempfile("alder-output-staging-")
  dir.create(td)

  source <- export_test_notebook(file.path(td, "source.R"))
  exported <- file.path(td, "exported.R")
  writeLines("export sentinel", exported, useBytes = TRUE)
  alder:::alder_export(source, "script", out = exported)
  expect_match(paste(readLines(exported, warn = FALSE), collapse = "\n"),
               "Generated by alder", fixed = TRUE)
  expect_false(any(readLines(exported, warn = FALSE) == "export sentinel"))
  markdown <- file.path(td, "report.md")
  alder:::alder_export(source, "md", out = markdown)
  expect_true(file.exists(markdown))
  expect_length(list.files(td, pattern = "^\\.alder-export", all.files = TRUE), 0L)

  conversion <- file.path(td, "conversion.qmd")
  writeLines(c("# Converted", "", "```{r}", "x <- 1", "```"), conversion,
             useBytes = TRUE)
  converted <- file.path(td, "converted.R")
  writeLines("convert sentinel", converted, useBytes = TRUE)
  alder:::alder_convert(conversion, out = converted)
  expect_true(inherits(alder:::read_notebook(converted), "alder_notebook"))
  expect_false(any(readLines(converted, warn = FALSE) == "convert sentinel"))
  expect_length(list.files(td, pattern = "^\\.alder-convert", all.files = TRUE), 0L)

  bad_export <- file.path(td, "bad-export.R")
  writeLines(c("# %% [markdown]", "not an R comment"), bad_export,
             useBytes = TRUE)
  export_dest <- file.path(td, "preserve-export.html")
  writeLines("keep export", export_dest, useBytes = TRUE)
  expect_error(alder:::alder_export(bad_export, "html", out = export_dest),
               class = "alder_error")
  expect_identical(readLines(export_dest, warn = FALSE), "keep export")

  bad_convert <- file.path(td, "bad-convert.qmd")
  writeLines(c("```{python}", "print('nope')", "```"), bad_convert,
             useBytes = TRUE)
  convert_dest <- file.path(td, "preserve-convert.R")
  writeLines("keep convert", convert_dest, useBytes = TRUE)
  expect_error(alder:::alder_convert(bad_convert, out = convert_dest),
               class = "alder_error")
  expect_identical(readLines(convert_dest, warn = FALSE), "keep convert")
  expect_length(list.files(
    td, pattern = "^\\.alder-(export|convert)", all.files = TRUE
  ), 0L)
})

test_that("headless exports reject every blocking diagnostic before effects or replacement", {
  td <- tempfile("alder-export-diagnostics-")
  dir.create(td)
  marker <- file.path(td, "must-not-run")
  literal <- function(value) paste(utils::capture.output(dput(value)), collapse = "")
  cases <- list(
    syntax = c("# %%", "if (", "# %%",
               paste0("writeLines('ran', ", literal(marker), ")")),
    duplicate = c(
      "# %%", "duplicated <- 1L", paste0("writeLines('ran', ", literal(marker), ")"),
      "# %%", "duplicated <- 2L"
    ),
    cycle = c(
      "# %%", "cycle_a <- cycle_b + 1L", paste0("writeLines('ran', ", literal(marker), ")"),
      "# %%", "cycle_b <- cycle_a + 1L"
    ),
    dynamic = c(
      "# %%", "target <- 'dynamic_name'", paste0(
        "assign(target, writeLines('ran', ", literal(marker), "))"
      )
    )
  )
  for (name in names(cases)) {
    source <- file.path(td, paste0(name, ".R"))
    writeLines(cases[[name]], source, useBytes = TRUE)
    for (format in alder:::export_formats) {
      destination <- file.path(td, paste0(name, "-", format, ".out"))
      sentinel <- charToRaw(paste0("preserve ", name, " ", format, "\n"))
      writeBin(sentinel, destination)
      err <- tryCatch(
        alder:::alder_export(source, format, out = destination,
                             include_code = TRUE),
        error = identity
      )
      expect_true(inherits(err, "alder_error"), info = paste(name, format))
      expect_identical(err$code, "export_failed")
      expect_match(conditionMessage(err), switch(
        name,
        syntax = "unexpected end of input",
        duplicate = "duplicate definition of duplicated",
        cycle = "dependency cycle",
        dynamic = "assign() requires"
      ), fixed = TRUE)
      expect_identical(readBin(destination, "raw", n = file.info(destination)$size),
                       sentinel)
      expect_false(file.exists(marker))
      expect_length(list.files(
        td, pattern = "^\\.alder-export", all.files = TRUE
      ), 0L)
    }
  }
})

test_that("Markdown sidecar changes can roll back without residue", {
  td <- tempfile("alder-markdown-sidecar-")
  dir.create(td)
  sidecar <- file.path(td, "report_files")
  dir.create(sidecar)
  writeLines("old", file.path(sidecar, "old.txt"), useBytes = TRUE)
  stage <- file.path(td, ".alder-export-files-stage")
  dir.create(stage)
  writeLines("new", file.path(stage, "new.txt"), useBytes = TRUE)

  transaction <- alder:::export_markdown_sidecar_commit(stage, sidecar)
  expect_true(file.exists(file.path(sidecar, "new.txt")))
  alder:::export_markdown_sidecar_rollback(transaction)
  expect_true(file.exists(file.path(sidecar, "old.txt")))
  expect_false(file.exists(file.path(sidecar, "new.txt")))
  expect_length(list.files(td, pattern = "^\\.alder-export-files-backup", all.files = TRUE), 0L)

  stage <- file.path(td, ".alder-export-files-stage-final")
  dir.create(stage)
  writeLines("new", file.path(stage, "new.txt"), useBytes = TRUE)
  transaction <- alder:::export_markdown_sidecar_commit(stage, sidecar)
  alder:::export_markdown_sidecar_finalize(transaction)
  expect_true(file.exists(file.path(sidecar, "new.txt")))
  expect_length(list.files(td, pattern = "^\\.alder-export-files-backup", all.files = TRUE), 0L)
})
