name: R package quality

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  check:
    name: R ${{ matrix.r }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        r: ['4.6.1', devel]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NOT_CRAN: "true"
      R_KEEP_PKG_SOURCE: "yes"
      _R_CHECK_FORCE_SUGGESTS_: "true"
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - uses: r-lib/actions/setup-r@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2
        with:
          r-version: ${{ matrix.r }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2
        with:
          dependencies: '"hard"'
          extra-packages: |
            any::rcmdcheck
            any::lintr
            any::pkgload
            any::testthat
            any::processx
            any::withr
            any::microbenchmark
      - name: Lint package
        if: matrix.r == '4.6.1'
        run: Rscript -e 'pkgload::load_all(quiet = TRUE); lints <- lintr::lint_package(); print(lints); quit(status = length(lints) > 0L)'

      - uses: r-lib/actions/check-r-package@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          build_args: 'c("--no-build-vignettes")'
          error-on: '"warning"'
